name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cc: [gcc, clang]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make clean build CC=${{ matrix.cc }}

      - name: Test
        run: make test CC=${{ matrix.cc }}
